general { 
    lock_cmd = hyprlock                              # dbus/sysd lock command (loginctl lock-session)
    ignore_dbus_inhibit = false                      # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false                   # whether to ignore systemd-inhibit --what=idle inhibitors
}

listener {
    timeout =  600                                   # in seconds
    on-timeout = hyprlock                            # command to run when timeout has passed
}

listener {
    timeout = 600                                   # Suspend 10 minutes after idle and sleep after 10 more set in the /etc/systemd/sleep.conf file 
    on-timeout = systemctl suspend-then-hibernate   # Trigger suspend and hibernate
}

