pcall(require, "impatient")

require("user.options")
require("user.keymaps")
require("user.colourscheme")

require("lsp.lsp")
require("lsp.null-ls")

require("plugins._plugins")
require("plugins.alpha")
require("plugins.autopairs")
require("plugins.cmp")
require("plugins.comment")
require("plugins.git-conflict")
require("plugins.gitsigns")
require("plugins.indent-blankline")
require("plugins.lualine")
require("plugins.luasnip")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.toggle-term")
require("plugins.treesitter")
require("plugins.whichkey")
