require("user.options")
require("user.keymaps")
require("user.colourscheme")

require("lsp.lsp")
require("lsp.null-ls")

require("plugins.plugins")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.nvim-tree")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.whichkey")
